{{- if and .Values.demoVerifier.enabled .Values.demoVerifier.ingress.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-demo-verifier
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: demo-verifier
spec:
  rules:
    - host: {{ .Values.demoVerifier.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" . }}-demo-verifier
                port:
                  number: 8090
{{- end }}
