apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.postgresFullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.postgresFullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
      - image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}{{ if .Values.postgres.image.digest }}@{{ .Values.postgres.image.digest }}{{ end }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy | quote }}
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.existingSecret | default (printf "%s-database" (include "app.fullname" .)) }}
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.existingSecret | default (printf "%s-database" (include "app.fullname" .)) }}
              key: user
        - name: POSTGRES_DB
          value: {{ .Values.database.name | quote }}
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql
        readinessProbe:
          exec:
            command:
            - pg_isready
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-data
        {{- if .Values.postgres.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.persistence.existingClaim | default (printf "%s-postgres" (include "app.fullname" .)) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
