{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-database
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.database.user | quote }}
  password: {{ .Values.database.password | quote }}
{{- end }}
