services:
  postgres:
    build:
      context: ./dockerfiles/
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tinycongress
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # app-test:
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/Dockerfile.test
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@postgres:5432/prioritization_test
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
