# yaml-language-server: $schema=https://raw.githubusercontent.com/GoogleContainerTools/skaffold/main/docs-v2/content/en/schemas/v4beta13.json
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: tiny-congress
build:
  local:
    push: false
    tryImportMissing: true
    useBuildkit: true
    concurrency: 3
  platforms:
    - "linux/arm64"
  artifacts:
    - image: tc-api-dev
      context: .
      docker:
        dockerfile: service/Dockerfile.dev
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
          RUST_VERSION: "{{.RUST_VERSION}}"
        cacheFrom:
          - "tc-api-dev:cache-main"
          - "tc-api-dev:cache"
      sync:
        manual:
          - src: "service/src/**/*.rs"
            dest: /usr/src/app
          - src: "service/migrations/**/*"
            dest: /usr/src/app
          - src: "service/Cargo.toml"
            dest: /usr/src/app
          - src: "Cargo.lock"
            dest: /usr/src/app
    - image: postgres
      context: .
      docker:
        dockerfile: dockerfiles/Dockerfile.postgres
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
        cacheFrom:
          - "postgres:cache-main"
          - "postgres:cache"
    - image: tc-ui-dev
      context: ./web/
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
        cacheFrom:
          - "tc-ui-dev:cache-main"
          - "tc-ui-dev:cache"
      sync:
        manual:
          - src: "src/**/*"
            dest: /app
          - src: "public/**/*"
            dest: /app
deploy:
  helm:
    releases:
      - name: tc
        chartPath: kube/app
        valuesFiles:
          - kube/app/values.yaml
        version: 0.1.0
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_tc_api_dev}}"
          image.tag: "{{.IMAGE_TAG_tc_api_dev}}"
          frontend.image.repository: "{{.IMAGE_REPO_tc_ui_dev}}"
          frontend.image.tag: "{{.IMAGE_TAG_tc_ui_dev}}"
          postgres.image.repository: "{{.IMAGE_REPO_postgres}}"
          postgres.image.tag: "{{.IMAGE_TAG_postgres}}"
        setValues:
          serviceAccount:
            create: false
          cargoCache:
            enabled: true
          # Enable dev tools in local development (disabled by default for security)
          graphql:
            playgroundEnabled: true
          swagger:
            enabled: true

# PRE-DEPLOY TESTS (cluster not required)
# - Rust: unit tests via cargo llvm-cov (auto-discovers all tests except integration tests)
# - Web: vitest unit tests
test:
  - image: tc-api-release
    custom:
      - command: |
          cd service
          mkdir -p coverage
          cargo llvm-cov clean --workspace
          cargo llvm-cov --lcov \
            --output-path coverage/backend-unit.lcov \
            --remap-path-prefix \
            -- --test-threads=1 --nocapture
  - image: tc-ui-release
    custom:
      - command: |
          cd web
          CI=true yarn vitest:coverage

# Ensure Postgres is reachable from localhost for developer workflows
portForward:
  - resourceType: service
    resourceName: postgres
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: tc
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: tc-frontend
    port: 5173
    localPort: 5173

profiles:
  # dev profile: uses dev Dockerfiles with hot-reload and file sync
  # Requires KinD cluster: kind create cluster && skaffold dev
  - name: dev
    build:
      local:
        push: false
  - name: release
    build:
      artifacts:
        - image: tc-api-release
          context: .
          docker:
            dockerfile: service/Dockerfile
        - image: tc-ui-release
          context: .
          docker:
            dockerfile: web/Dockerfile
  - name: ci
    build:
      local:
        push: true
      platforms:
        - "linux/amd64"
      artifacts:
        - image: tc-api-release
          context: .
          docker:
            dockerfile: service/Dockerfile
            buildArgs:
              BUILDKIT_INLINE_CACHE: "1"
              RUST_VERSION: "{{.RUST_VERSION}}"
            cacheFrom:
              - "tc-api-release:cache-main"
              - "tc-api-release:cache"
        - image: postgres
          context: .
          docker:
            dockerfile: dockerfiles/Dockerfile.postgres
            buildArgs:
              BUILDKIT_INLINE_CACHE: "1"
            cacheFrom:
              - "postgres:cache-main"
              - "postgres:cache"
        - image: tc-ui-release
          context: .
          docker:
            dockerfile: web/Dockerfile
            buildArgs:
              BUILDKIT_INLINE_CACHE: "1"
              RUST_VERSION: "{{.RUST_VERSION}}"
            cacheFrom:
              - "tc-ui-release:cache-main"
              - "tc-ui-release:cache"
    deploy:
      helm:
        releases:
          - name: tc
            chartPath: kube/app
            valuesFiles:
              - kube/app/values.yaml
            version: 0.1.0
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_tc_api_release}}"
              image.tag: "{{.IMAGE_TAG_tc_api_release}}"
              frontend.image.repository: "{{.IMAGE_REPO_tc_ui_release}}"
              frontend.image.tag: "{{.IMAGE_TAG_tc_ui_release}}"
              postgres.image.repository: "{{.IMAGE_REPO_postgres}}"
              postgres.image.tag: "{{.IMAGE_TAG_postgres}}"
              buildInfo.appVersion: "{{ .APP_VERSION }}"
              buildInfo.gitSha: "{{ .GIT_SHA }}"
              buildInfo.buildTime: "{{ .BUILD_TIME }}"
            setValues:
              serviceAccount:
                create: false
              frontend.service.port: 80
              frontend.service.targetPort: 80
