apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: prioritization-room
build:
  platforms: ["linux/arm64"]
  artifacts:
    - image: tc-api
      context: ./service/
      docker:
        dockerfile: ./dockerfiles/Dockerfile.backend
    - image: postgres
      context: .
      docker:
        dockerfile: ./dockerfiles/Dockerfile.postgres
    - image: tc-ui-dev
      context: ./web/
      docker:
        dockerfile: ./dockerfiles/Dockerfile.frontend-dev
    - image: tc-ui-release
      context: ./web/
      docker:
        dockerfile: ./dockerfiles/Dockerfile.frontend
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
profiles:
  - name: dev
    build:
      local:
        push: false
    deploy:
      kubectl: {}
  - name: test
    build:
      local:
        push: false
    test:
      - image: tc-api
        custom:
          command: cargo test --test integration_tests -- --test-threads=1 --nocapture
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/prioritization_test
