apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: prioritization-room
build:
  platforms: ["linux/arm64"]
  artifacts:
    - image: tc-api-dev
      context: ./service/
      docker:
        dockerfile: ./dockerfiles/Dockerfile.backend-dev
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
    - image: postgres
      context: .
      docker:
        dockerfile: ./dockerfiles/Dockerfile.postgres
    - image: tc-ui-dev
      context: ./web/
      docker:
        dockerfile: ./dockerfiles/Dockerfile.frontend-dev
deploy:
  helm:
    releases:
      - name: tc
        chartPath: kube/app
        valuesFiles:
          - kube/app/values.yaml
        version: 0.1.0
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_tc_api_dev}}"
          image.tag: "{{.IMAGE_TAG_tc_api_dev}}"
          frontend.image.repository: "{{.IMAGE_REPO_tc_ui_dev}}"
          frontend.image.tag: "{{.IMAGE_TAG_tc_ui_dev}}"

# Pre-deploy tests: run fast unit/API/UI tests only
test:
  - image: tc-api-dev
    custom:
      - command: cd service && cargo test --test api_tests --test graphql_tests --test model_tests -- --test-threads=1 --nocapture
  - image: tc-ui-dev
    custom:
      - command: cd web && yarn install --frozen-lockfile && yarn test

# Post-deploy verification: run integration tests against the live cluster
verify:
  - name: integration-tests
    container:
      name: integration-tests
      image: tc-api-dev
      command: ["/bin/sh"]
      args: ["-lc", "cd /usr/src/app && DATABASE_URL=postgres://postgres:postgres@postgres:5432/prioritization cargo test --test integration_tests -- --test-threads=1 --nocapture"]
    executionMode:
      kubernetesCluster: {}

# Ensure Postgres is reachable from localhost for developer workflows
portForward:
  - resourceType: service
    resourceName: postgres
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: tc
    port: 80
    localPort: 8080
  - resourceType: deployment
    resourceName: tc-frontend
    port: 5173
    localPort: 5173

profiles:
  - name: dev
    build:
      local:
        push: false
    deploy:
      kubectl: {}
  - name: release
    build:
      artifacts:
        - image: tc-api-release
          context: ./service/
          docker:
            dockerfile: ./dockerfiles/Dockerfile.backend
        - image: tc-ui-release
          context: ./web/
          docker:
            dockerfile: ./dockerfiles/Dockerfile.frontend
