apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: prioritization-room
build:
  platforms: ["linux/arm64"]
  artifacts:
    - image: tc-api-release
      context: ./service/
      docker:
        dockerfile: ./dockerfiles/Dockerfile.backend
    - image: tc-api-dev
      context: ./service/
      docker:
        dockerfile: ./dockerfiles/Dockerfile.backend-dev
    - image: postgres
      context: .
      docker:
        dockerfile: ./dockerfiles/Dockerfile.postgres
    - image: tc-ui-dev
      context: ./web/
      docker:
        dockerfile: ./dockerfiles/Dockerfile.frontend-dev
    - image: tc-ui-release
      context: ./web/
      docker:
        dockerfile: ./dockerfiles/Dockerfile.frontend
deploy:
  helm:
    releases:
      - name: tc
        chartPath: kube/app
        valuesFiles:
          - kube/app/values.yaml
        version: 0.1.0
test:
  - image: tc-api-dev
    custom:
      - command: cd service && cargo test -- --test-threads=1 --nocapture
  - image: tc-ui-dev
    custom:
      - command: cd web && yarn test
profiles:
  - name: dev
    build:
      local:
        push: false
    deploy:
      kubectl: {}
