#!/usr/bin/env python3
"""Generate Grafana dashboard JSON from Foundation SDK definitions.

Usage:
    python kube/dashboards/generate.py            # generate + validate
    python kube/dashboards/generate.py --check     # validate only (no write)

Output is written to kube/app/files/dashboards/ so Helm's .Files.Get can reach it.
"""

import argparse
import json
import sys
from pathlib import Path

from grafana_foundation_sdk.cog.encoder import JSONEncoder

import health

CHART_DIR = Path(__file__).parent.parent / "app"
OUTPUT_DIR = CHART_DIR / "files" / "dashboards"


def validate(data: dict) -> list[str]:
    """Return a list of validation errors (empty = pass)."""
    errors = []

    if data.get("title") != "Tiny Congress Health":
        errors.append(f"unexpected title: {data.get('title')}")

    panels = data.get("panels", [])
    # v1 format: row panels with nested content panels
    row_panels = [p for p in panels if p.get("type") == "row"]
    # Content panels may be nested inside rows or at top level
    content_panels = [p for p in panels if p.get("type") != "row"]
    for rp in row_panels:
        content_panels.extend(rp.get("panels", []))

    if len(row_panels) != 5:
        errors.append(f"expected 5 row panels, got {len(row_panels)}")

    if len(content_panels) < 10:
        errors.append(f"expected >=10 content panels, got {len(content_panels)}")

    # Check all content panels have gridPos
    for p in content_panels:
        if "gridPos" not in p:
            errors.append(f"panel '{p.get('title', '?')}' missing gridPos")

    variables = data.get("templating", {}).get("list", [])
    var_names = {v.get("name") for v in variables}
    for required in ("namespace", "prometheus_datasource", "loki_datasource"):
        if required not in var_names:
            errors.append(f"missing variable: {required}")

    return errors


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="validate without writing")
    args = parser.parse_args()

    dashboard = health.build()
    built = dashboard.build()
    rendered = json.loads(json.dumps(built, cls=JSONEncoder))

    errors = validate(rendered)
    if errors:
        for e in errors:
            print(f"FAIL: {e}", file=sys.stderr)
        sys.exit(1)

    panels = rendered.get("panels", [])
    row_count = sum(1 for p in panels if p.get("type") == "row")
    content_count = sum(len(p.get("panels", [])) for p in panels if p.get("type") == "row")
    content_count += sum(1 for p in panels if p.get("type") != "row")
    print(f"OK: {content_count} panels, {row_count} rows")

    if not args.check:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        out_path = OUTPUT_DIR / "health.json"
        # Inject a DO-NOT-EDIT marker at the top of the JSON object so the file
        # is self-documenting. Grafana ignores unknown root-level keys.
        output = {"__DO_NOT_EDIT__": "Generated by kube/dashboards/health.py — run: just generate-dashboards"}
        output.update(json.loads(json.dumps(built, cls=JSONEncoder)))
        out_path.write_text(json.dumps(output, indent=2, sort_keys=False) + "\n")
        print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
