FROM rust:1.86 as builder

WORKDIR /usr/src/app
COPY . .

RUN cargo install sqlx-cli
RUN cargo sqlx prepare --check
RUN cargo build --release

FROM debian:bullseye-slim

RUN apt-get update \
  && apt-get install -y ca-certificates libpq5 libssl1.1 \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/app/target/release/tinycongress-api /usr/local/bin/
COPY --from=builder /usr/src/app/target/release/client /usr/local/bin/

ENV SQLX_OFFLINE=true

CMD ["tinycongress-api"]
