apiVersion: batch/v1
kind: Job
metadata:
  name: integration-tests
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: integration-tests
    spec:
      restartPolicy: Never
      containers:
        - name: integration-tests
          image: tc-api-dev
          command: ["/bin/sh", "-lc"]
          args:
            - |
              cd /usr/src/app
              ./bin/integration-coverage.sh
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/prioritization
            - name: ARTIFACTS_DIR
              value: /artifacts
            - name: EXPORT_LCOV_BASE64
              value: "0"
          volumeMounts:
            - name: test-artifacts
              mountPath: /artifacts
      volumes:
        - name: test-artifacts
          persistentVolumeClaim:
            claimName: test-artifacts-pvc
