//! Trust graph simulation harness for Sybil resistance testing.
//!
//! Constructs adversarial graph topologies with red/blue team designations
//! and runs the real `TrustEngine` against them.
//!
//! ## Architecture
//!
//! - [`GraphSpec`] — pure data: nodes, edges, team designations. No DB, no side effects.
//!   Can be constructed programmatically, generated by proptest, or deserialized.
//! - [`GraphBuilder`] — materializes a `GraphSpec` into real database rows (accounts,
//!   endorsements) for running the trust engine against.

pub mod comparison;
pub mod generators;
pub mod mechanisms;
pub mod predicates;
pub mod report;
pub mod topology;

use std::collections::HashMap;
use std::ops::{Deref, DerefMut};

use sqlx::PgPool;
use uuid::Uuid;

use crate::common::factories::{insert_endorsement, insert_revoked_endorsement, AccountFactory};

/// Team designation for simulation nodes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Team {
    /// Legitimate users — expected to pass trust thresholds.
    Blue,
    /// Adversarial users — expected to be blocked by trust mechanisms.
    Red,
}

impl std::fmt::Display for Team {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Blue => write!(f, "Blue"),
            Self::Red => write!(f, "Red"),
        }
    }
}

/// A node in the simulation graph with team metadata.
#[derive(Debug, Clone)]
pub struct SimNode {
    pub id: Uuid,
    pub name: String,
    pub team: Team,
}

/// A directed edge in the simulation graph.
#[derive(Debug, Clone)]
pub struct SimEdge {
    pub from: Uuid,
    pub to: Uuid,
    pub weight: f32,
    pub revoked: bool,
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
}

// ---------------------------------------------------------------------------
// GraphSpec — pure graph description (no DB, no side effects)
// ---------------------------------------------------------------------------

/// Pure graph description: nodes, edges, and team designations.
///
/// This is the data layer of the simulation. It can be:
/// - Built programmatically via `add_node` / `add_edge`
/// - Generated randomly by proptest's `Arbitrary`
/// - Passed to predicates for behavioral invariant checking
/// - Serialized/deserialized for reproducible test cases
#[derive(Clone)]
pub struct GraphSpec {
    nodes: Vec<SimNode>,
    edges: Vec<SimEdge>,
    name_to_id: HashMap<String, Uuid>,
}

impl GraphSpec {
    pub fn new() -> Self {
        Self {
            nodes: Vec::new(),
            edges: Vec::new(),
            name_to_id: HashMap::new(),
        }
    }

    /// Add a node to the spec with a pre-assigned ID.
    ///
    /// Use this when building specs without a database (e.g., proptest).
    /// For DB-backed construction, use `GraphBuilder::add_node` instead.
    pub fn add_node(&mut self, name: &str, team: Team, id: Uuid) {
        self.nodes.push(SimNode {
            id,
            name: name.to_string(),
            team,
        });
        self.name_to_id.insert(name.to_string(), id);
    }

    /// Add a directed edge to the spec.
    pub fn add_edge(&mut self, from: Uuid, to: Uuid, weight: f32) {
        self.edges.push(SimEdge {
            from,
            to,
            weight,
            revoked: false,
            created_at: None,
        });
    }

    /// Add a pre-revoked edge to the spec.
    pub fn add_edge_revoked(&mut self, from: Uuid, to: Uuid, weight: f32) {
        self.edges.push(SimEdge {
            from,
            to,
            weight,
            revoked: true,
            created_at: None,
        });
    }

    /// Mark an edge as revoked in-memory.
    pub fn revoke_edge(&mut self, from: Uuid, to: Uuid) {
        if let Some(edge) = self
            .edges
            .iter_mut()
            .find(|e| e.from == from && e.to == to && !e.revoked)
        {
            edge.revoked = true;
        }
    }

    pub fn node(&self, name: &str) -> Uuid {
        *self
            .name_to_id
            .get(name)
            .unwrap_or_else(|| panic!("No node named '{name}'"))
    }

    pub fn nodes_by_team(&self, team: Team) -> Vec<Uuid> {
        self.nodes
            .iter()
            .filter(|n| n.team == team)
            .map(|n| n.id)
            .collect()
    }

    pub fn all_nodes(&self) -> &[SimNode] {
        &self.nodes
    }

    pub fn all_edges(&self) -> &[SimEdge] {
        &self.edges
    }

    pub fn node_name(&self, id: Uuid) -> &str {
        self.nodes
            .iter()
            .find(|n| n.id == id)
            .map(|n| n.name.as_str())
            .unwrap_or("unknown")
    }

    /// Count of active (non-revoked) edges.
    pub fn active_edge_count(&self) -> usize {
        self.edges.iter().filter(|e| !e.revoked).count()
    }

    /// Active inbound edges to a node.
    pub fn inbound_edges(&self, node_id: Uuid) -> Vec<&SimEdge> {
        self.edges
            .iter()
            .filter(|e| e.to == node_id && !e.revoked)
            .collect()
    }

    /// Active outbound edges from a node.
    pub fn outbound_edges(&self, node_id: Uuid) -> Vec<&SimEdge> {
        self.edges
            .iter()
            .filter(|e| e.from == node_id && !e.revoked)
            .collect()
    }

    /// Number of distinct endorsers of a node (active edges only).
    pub fn endorser_count(&self, node_id: Uuid) -> usize {
        self.inbound_edges(node_id).len()
    }

    /// Add an edge with a specific creation timestamp.
    pub fn add_edge_at(
        &mut self,
        from: Uuid,
        to: Uuid,
        weight: f32,
        created_at: chrono::DateTime<chrono::Utc>,
    ) {
        self.edges.push(SimEdge {
            from,
            to,
            weight,
            revoked: false,
            created_at: Some(created_at),
        });
    }

    /// Mutable access to all edges (used by topology helpers to set timestamps).
    pub fn all_edges_mut(&mut self) -> &mut Vec<SimEdge> {
        &mut self.edges
    }

    /// Apply time decay to all edges based on their age relative to `now`.
    ///
    /// `decay_fn` takes the edge age (as Duration) and returns a weight multiplier
    /// in [0.0, 1.0]. Edges whose decayed weight falls below `min_weight` are
    /// clamped to `min_weight` (not removed).
    pub fn apply_decay(
        &mut self,
        now: chrono::DateTime<chrono::Utc>,
        decay_fn: impl Fn(chrono::Duration) -> f32,
        min_weight: f32,
    ) {
        for edge in &mut self.edges {
            if edge.revoked {
                continue;
            }
            if let Some(created) = edge.created_at {
                let age = now - created;
                let multiplier = decay_fn(age).clamp(0.0, 1.0);
                edge.weight = (edge.weight * multiplier).max(min_weight);
            }
        }
    }

    /// Create a snapshot of the spec at a given time, with decay applied.
    ///
    /// Returns a new `GraphSpec` with decayed weights; does not modify `self`.
    pub fn with_decay(
        &self,
        now: chrono::DateTime<chrono::Utc>,
        decay_fn: impl Fn(chrono::Duration) -> f32,
        min_weight: f32,
    ) -> Self {
        let mut spec = self.clone();
        spec.apply_decay(now, decay_fn, min_weight);
        spec
    }
}

impl Default for GraphSpec {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// GraphBuilder — materializes a GraphSpec into the database
// ---------------------------------------------------------------------------

/// Materializes a [`GraphSpec`] into real database rows for engine testing.
///
/// Wraps a `GraphSpec` and a `PgPool`. Mutations (add_node, endorse, revoke)
/// write to both the in-memory spec and the database. Pure queries delegate
/// to the spec via `Deref`.
pub struct GraphBuilder {
    spec: GraphSpec,
    pool: PgPool,
}

impl GraphBuilder {
    pub fn new(pool: PgPool) -> Self {
        Self {
            spec: GraphSpec::new(),
            pool,
        }
    }

    /// Access the underlying graph spec.
    pub fn spec(&self) -> &GraphSpec {
        &self.spec
    }

    /// Mutable access to the underlying graph spec.
    pub fn spec_mut(&mut self) -> &mut GraphSpec {
        &mut self.spec
    }

    pub async fn add_node(&mut self, name: &str, team: Team) -> Uuid {
        let account = AccountFactory::new()
            .with_username(name)
            .create(&self.pool)
            .await
            .unwrap_or_else(|e| panic!("Failed to create account '{name}': {e}"));

        self.spec.add_node(name, team, account.id);
        account.id
    }

    pub async fn endorse(&mut self, from: Uuid, to: Uuid, weight: f32) {
        insert_endorsement(&self.pool, from, to, weight).await;
        self.spec.add_edge(from, to, weight);
    }

    pub async fn endorse_revoked(&mut self, from: Uuid, to: Uuid, weight: f32) {
        insert_revoked_endorsement(&self.pool, from, to, weight).await;
        self.spec.add_edge_revoked(from, to, weight);
    }

    /// Revoke an existing endorsement (set revoked_at = now()).
    ///
    /// Panics if no active endorsement exists from→to.
    pub async fn revoke(&mut self, from: Uuid, to: Uuid) {
        let result = sqlx::query(
            "UPDATE reputation__endorsements SET revoked_at = now() \
             WHERE endorser_id = $1 AND subject_id = $2 AND topic = 'trust' AND revoked_at IS NULL",
        )
        .bind(from)
        .bind(to)
        .execute(&self.pool)
        .await
        .expect("revoke endorsement query failed");
        assert_eq!(
            result.rows_affected(),
            1,
            "expected to revoke exactly 1 endorsement from {} to {}",
            from,
            to
        );
        self.spec.revoke_edge(from, to);
    }

    pub fn pool(&self) -> &PgPool {
        &self.pool
    }
}

/// `GraphBuilder` auto-derefs to `GraphSpec` for read access.
///
/// This means `g.all_nodes()`, `g.node("anchor")`, `g.all_edges()`, etc.
/// work seamlessly on a `GraphBuilder` without callers needing to know
/// about the spec/builder separation.
impl Deref for GraphBuilder {
    type Target = GraphSpec;
    fn deref(&self) -> &GraphSpec {
        &self.spec
    }
}

impl DerefMut for GraphBuilder {
    fn deref_mut(&mut self) -> &mut GraphSpec {
        &mut self.spec
    }
}
