/**
 * Type declarations for WASM crypto module.
 * This file provides types for CI where the WASM module is built after linting.
 * The actual type declarations are generated by wasm-pack in src/wasm/tc-crypto/tc_crypto.d.ts
 */

declare module '@/wasm/tc-crypto/tc_crypto.js' {
  /**
   * Decode a base64url-encoded string (RFC 4648) to bytes.
   */
  export function decode_base64url(encoded: string): Uint8Array;

  /**
   * Derive a key identifier (KID) from a public key.
   * The KID is computed as: `base64url(SHA-256(pubkey)[0:16])`
   */
  export function derive_kid(public_key: Uint8Array): string;

  /**
   * Encode bytes as base64url (RFC 4648) without padding.
   */
  export function encode_base64url(bytes: Uint8Array): string;

  /**
   * Initialize the WASM module. Must be called before using exported functions.
   */
  export default function init(): Promise<void>;

  /**
   * Synchronously initialize the WASM module from a buffer.
   * Used in Node.js test environment where fetch-based loading doesn't work.
   */
  export function initSync(input: { module: BufferSource } | BufferSource): void;
}
