import type { StorybookConfig } from '@storybook/react-vite';
import type { InlineConfig } from 'vite';

const config: StorybookConfig = {
  core: {
    disableWhatsNewNotifications: true,
    disableTelemetry: true,
    enableCrashReports: false,
  },
  stories: ['../src/**/*.mdx', '../src/**/*.story.@(js|jsx|ts|tsx)'],
  addons: ['@vueless/storybook-dark-mode'],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  viteFinal(config: InlineConfig): InlineConfig {
    // The tc-crypto WASM module is generated by wasm-pack and gitignored.
    // It is not available during the Storybook build in CI (no Rust toolchain),
    // so we tell Rollup to treat it as external rather than try to bundle it.
    // Components that use useCrypto() will never reach the dynamic import in
    // Storybook because stories run without a real CryptoProvider.
    return {
      ...config,
      build: {
        ...config.build,
        rollupOptions: {
          ...config.build?.rollupOptions,
          external: [
            ...(Array.isArray(config.build?.rollupOptions?.external)
              ? config.build.rollupOptions.external
              : []),
            /wasm\/tc-crypto\/.*/,
          ],
        },
      },
    };
  },
};

export default config;
