name: skaffold verify

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  skaffold_verify:
    name: Run skaffold verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: enable cross-arch builds if needed. Commented by default.
      # - name: Set up QEMU (for cross-arch builds)
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Set up KinD cluster
        uses: helm/kind-action@v1.10.0
        with:
          version: v0.22.0
          kubectl_version: v1.30.0
          cluster_name: skaffold-ci

      - name: Install Skaffold
        run: |
          set -euo pipefail
          SKAFFOLD_VERSION=v2.15.0
          curl -fsSL -o skaffold https://storage.googleapis.com/skaffold/releases/${SKAFFOLD_VERSION}/skaffold-linux-amd64
          echo "Installing skaffold ${SKAFFOLD_VERSION}"
          sudo install skaffold /usr/local/bin/skaffold
          skaffold version

      - name: Warm yarn cache (UI tests in verify may run yarn during build)
        uses: actions/setup-node@v4
        with:
          node-version-file: 'web/.nvmrc'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Show cluster info
        run: |
          kubectl version --client=true
          kubectl cluster-info
          kubectl get nodes -o wide

      - name: Build & deploy to KinD (ci profile)
        env:
          # Use the dedicated CI profile to build linux/amd64 images on GitHub runners
          SKAFFOLD_PROFILE: ci
        run: |
          set -euo pipefail
          skaffold run -p ${SKAFFOLD_PROFILE} --status-check=false

      - name: Run skaffold verify
        env:
          SKAFFOLD_PROFILE: ci
        run: |
          set -euo pipefail
          skaffold verify -p ${SKAFFOLD_PROFILE}

      - name: Dump diagnostics on failure
        if: failure()
        run: |
          echo '--- Pods ---'
          kubectl get pods -A -o wide || true
          echo '--- Services ---'
          kubectl get svc -A || true
          echo '--- Events ---'
          kubectl get events -A --sort-by=.lastTimestamp || true
          echo '--- Helm Releases ---'
          kubectl get all -n default || true
